### ISSUE TITLE
Plate issue (jlcpcb)

### ISSUE THREAD

**Issue by Kejchi** [Ladniy/jiran#3]
Maybe you should change the plate gerber file?
![Screenshot_20211214-095049_1](https://user-images.githubusercontent.com/24889523/145912662-f393a0d7-317e-4702-a31a-9d762c390094.jpg)

**Comment by Ladniy** [comment]
No. You must write to them "cut them as non-plated slot". This follows from their message.
This is problem with JLCPCB only, other fabric have no problems with this footprint.
